### ISSUE TITLE
Update PRAW and Mage AI

### ISSUE THREAD

**Issue by LakshmanRaajS** [LakshmanRaajS/Safe-Feed#6]
Update PRAW and Mage AI for checking for new posts on subreddit.

**Comment by NishanthPrasath** [comment]
- Check for posts on a regular interval
- Scrape Image and Text separately
- Run Perspective API and OpenAI API for text
- Explore models for Image?
- Store the data into Snowflake

**Comment by NishanthPrasath** [comment]
Implemented code to pull posts from Reddit and check their text content for moderation using the OpenAI and Perspective APIs. Images are passed to the WD Tagger Model to obtain their tags. The data is then stored in Snowflake.
